var zzindex,trackedObject=null,trackedOrigStyle="",_hidePointLabel=[],_hidePointTrace=[];function toggleTracked(a){trackedObject!=null&&clearTracking(trackedObject);a==trackedObject?trackedObject=null:(trackedObject=a,setTracking(a))}function setTracking(a){x=document.getElementById(a+"_label_txt");if(x!=null)trackedOrigStyle=x.className,x.className+=" tracked"}function clearTracking(a){x=document.getElementById(a+"_label_txt");if(x!=null)x.className=trackedOrigStyle}
function isTracked(a){return a==trackedObject}function hidePointLabel(a){_hidePointLabel[a]=!0;a=document.getElementById(a+"_label_txt");if(a!=null)a.style.visibility="hidden"}function showPointLabel(a){_hidePointLabel[a]=!1;a=document.getElementById(a+"_label_txt");if(a!=null)a.style.visibility="visible"}function labelIsHidden(a){return _hidePointLabel[a]==!0}function hasTrace(a){return document.getElementById(a+"_trace")!=null}
kaXmlOverlay.prototype._setPointTrace=function(a,b){function c(a,b){var c=document.getElementById(a+"_trace");if(c!=null)c.style.visibility=b?"hidden":"visible"}if(a=="ALL")for(var d=0;d<this.ovrObjects.length;d++)c(this.ovrObjects[d].pid,b);else{if(_hidePointTrace.ALL)return;c(a,b)}_hidePointTrace[a]=b};kaXmlOverlay.prototype.hidePointTrace=function(a){this._setPointTrace(a,!0)};kaXmlOverlay.prototype.showPointTrace=function(a){this._setPointTrace(a,!1)};
function traceIsHidden(a){return _hidePointTrace[a]==!0}
function kaXmlOverlay(a,b){kaTool.apply(this,[a]);this.name="kaXmlOverlay";this.postLoadXml=null;this.meta=[];for(var c in kaTool.prototype)kaXmlOverlay.prototype[c]||(kaXmlOverlay.prototype[c]=kaTool.prototype[c]);this.urlBase=this.kaMap.server;this.urlBase+=this.urlBase!=""&&this.urlBase.substring(-1)!="/"?"":"/";this.ovrObjects=[];zzindex=this.z_index=b;this.overlayCanvas=this.kaMap.createDrawingCanvas(b,!0);this.kaMap.registerForEvent(KAMAP_SCALE_CHANGED,this,this.scaleChanged)}
kaXmlOverlay.prototype.scaleChanged=function(){if(this.ovrObjects!=null)for(var a=0;a<this.ovrObjects.length;a++)this.ovrObjects[a]&&this.ovrObjects[a].rescale()};kaXmlOverlay.prototype.remove=function(){this.kaMap.deregisterForEvent(KAMAP_SCALE_CHANGED,this,this.scaleChanged);this.removePoint();this.kaMap.removeDrawingCanvas(this.overlayCanvas)};kaXmlOverlay.prototype.loadXml=function(a){return call(a,this,this.loadXmlCallback,!0)};
if(typeof DOMParser=="undefined")DOMParser=function(){},DOMParser.prototype.parseFromString=function(a,b){if(typeof ActiveXObject!="undefined"){var c=new ActiveXObject("MSXML.DomDocument");c.loadXML(a);return c}else if(typeof XMLHttpRequest!="undefined")return c=new XMLHttpRequest,c.open("GET","data:"+(b||"application/xml")+";charset=utf-8,"+encodeURIComponent(a),!1),c.overrideMimeType&&c.overrideMimeType(b),c.send(null),c.responseXML};
kaXmlOverlay.prototype.loadXmlCallback=function(a){this.loadXmlDoc(a)&&postLoadXml()};var lastOvrSeq=0;
kaXmlOverlay.prototype.loadXmlDoc=function(a){if(a.length<10)return!1;var a=(new DOMParser).parseFromString(a,"text/xml").documentElement,b=a.getAttribute("cancel"),c=a.getAttribute("reboot");if(c&&c=="true")return setTimeout(function(){window.location.reload()},25E3),!1;if(b&&b=="true")return!1;if(b=a.getAttribute("seq")){b=parseInt(b);if(b>0&&b<=lastOvrSeq)return!1;lastOvrSeq=b}if((b=a.getAttribute("view"))&&b!=selectedFView)return OpenLayers.Console.info("LOAD XML: View name mismatch -> IGNORE"),
!1;c=a.getElementsByTagName("meta");for(b=0;b<c.length;b++){var d=c[b].getAttribute("name");if(d){var e=c[b].getAttribute("value");e&&(this.meta[d]=e)}}c=a.getElementsByTagName("delete");for(b=0;b<c.length;b++)(d=c[b].getAttribute("id"))?this.removePoint(d):this.removePoint();c=!1;a=a.getElementsByTagName("point");for(b=0;b<a.length;b++)if(d=a[b].getAttribute("id"))c=d,d=this.getPointObject(c),d==null&&(d=new kaXmlPoint(c,this),this.ovrObjects.push(d)),d.parse(a[b]),c=!0;c&&this.kaMap.updateObjects();
return!0};kaXmlOverlay.prototype.urlNormalize=function(a){return server_url+a};kaXmlOverlay.prototype.getDiv=function(a){a=this.getDivId(a);return getRawObject(a)};kaXmlOverlay.prototype.getPointObject=function(a){for(var b=0;b<this.ovrObjects.length;b++)if(this.ovrObjects[b]!=null&&this.ovrObjects[b].pid==a)return this.ovrObjects[b];return null};kaXmlOverlay.prototype.addNewPoint=function(a,b,c){this.removePoint(a);a=new kaXmlPoint(a,this);a.placeOnMap(b,c);this.ovrObjects.push(a);return a};
kaXmlOverlay.prototype.getDivId=function(a){return"xmlovr_"+a+"_div"};
kaXmlOverlay.prototype.removePoint=function(a){if(this.removePoint.arguments.length<1||a==null)for(a=this.ovrObjects.length;a-- >0;)this.ovrObjects[a]!=null&&(this.ovrObjects[a].removeFromMap(),delete this.ovrObjects[a],this.ovrObjects[a]=null),this.ovrObjects.splice(a,1);else for(var b=RegExp(a),a=this.ovrObjects.length;a-- >0;)this.ovrObjects[a]!=null?b.test(this.ovrObjects[a].pid)&&(this.ovrObjects[a].removeFromMap(),delete this.ovrObjects[a],this.ovrObjects[a]=null,this.ovrObjects.splice(a,1)):
this.ovrObjects.splice(a,1)};kaXmlOverlay.prototype.removePointGeo=function(a,b,c,d){for(var e=this.ovrObjects.length;e-- >0;){var f=this.ovrObjects[e];if(f!=null){if(f.geox<a||f.geoy<b||f.geox>c||f.geoy>d)f.removeFromMap(),delete f,this.ovrObjects[e]=null,this.ovrObjects.splice(e,1)}else this.ovrObjects.splice(e,1)}};function kaXmlGraphicElement(){}kaXmlGraphicElement.prototype.parseElement=function(){};kaXmlGraphicElement.prototype.draw=function(){};kaXmlGraphicElement.prototype.rescale=function(){};
kaXmlGraphicElement.prototype.remove=function(){};function kaXmlSymbol(){kaXmlGraphicElement.apply(this);_BrowserIdent_hasCanvasSupport()&&(kaXmlSymbol.prototype.draw=kaXmlSymbol.prototype.draw_canvas);for(var a in kaXmlGraphicElement.prototype)kaXmlSymbol.prototype[a]||(kaXmlSymbol.prototype[a]=kaXmlGraphicElement.prototype[a]);this.shape="bullet";this.size=10;this.stroke=1;this.bcolor=this.color=null;this.opacity=1;this.ldiv=this.canvas=null}
kaXmlSymbol.prototype.remove=function(){this.ldiv=this.canvas=null};kaXmlSymbol.prototype.parseElement=function(a,b){this.shape=b.getAttribute("shape");this.size=parseInt(b.getAttribute("size"));var c=b.getAttribute("color");if(c!=null)this.color=c;c=b.getAttribute("bcolor");if(c!=null)this.bcolor=c;c=parseFloat(b.getAttribute("opacity"));if(!isNaN(c))this.opacity=c;c=parseInt(b.getAttribute("stroke"));if(!isNaN(c))this.stroke=c};
kaXmlSymbol.prototype.draw_canvas=function(a){var b=Math.floor((this.size+this.stroke)/2);if(this.canvas==null)this.ldiv=document.createElement("div"),this.ldiv.style.position="absolute",this.ldiv.style.left=-b+"px",this.ldiv.style.top=-b+"px",a.div.appendChild(this.ldiv),this.canvas=_BrowserIdent_newCanvas(this.ldiv),_BrowserIdent_setCanvasHW(this.canvas,b*2,b*2);a=_BrowserIdent_getCanvasContext(this.canvas);a.save();a.translate(b,b);a.globalAlpha=this.opacity;a.lineWidth=this.stroke;if(this.bcolor)a.strokeStyle=
this.bcolor;if(this.color)a.fillStyle=this.color;this.shape=="square"?(this.color&&a.fillRect(-this.size/2,-this.size/2,this.size,this.size),this.bcolor&&a.strokeRect(-this.size/2,-this.size/2,this.size,this.size)):(a.beginPath(),a.arc(0,0,this.size/2,0,Math.PI*2,!1),this.color&&a.fill(),this.bcolor&&a.stroke());a.restore()};
function kaXmlFeature(a){kaXmlGraphicElement.apply(this);for(var b in kaXmlGraphicElement.prototype)kaXmlFeature.prototype[b]||(kaXmlFeature.prototype[b]=kaXmlGraphicElement.prototype[b]);this.stroke=1;this.bcolor=this.color2=this.color=null;this.opacity=1;this.cxmax=this.cymin=this.cymax=this.cxmin=0;this.coords="";this.yn=this.xn=this.ldiv=this.canvas=this.img=null;this.maxScale=a.xml_overlay.kaMap.getMaxScale();this.mcs=a.xml_overlay.kaMap.getResolution()/(a.xml_overlay.kaMap.getCurrentScale()/
this.maxScale)}kaXmlFeature.prototype.remove=function(){this.coords=this.ldiv=this.canvas=this.img=null;this.xn.splice(0);this.yn.splice(0)};
kaXmlFeature.prototype.parseElement=function(a,b){var c;c=parseInt(b.getAttribute("stroke"));if(!isNaN(c))this.stroke=c;c=b.getAttribute("color");if(c!=null)this.color=c;c=b.getAttribute("color2");if(c!=null)this.color2=c;c=b.getAttribute("bcolor");if(c!=null)this.bcolor=c;c=parseFloat(b.getAttribute("opacity"));if(!isNaN(c))this.opacity=c;c="";if(b.firstChild!=null)c=b.firstChild.data,this.readCoordinates(a,c)};
kaXmlFeature.prototype.readCoordinates=function(a,b){var c=[],d=[],e=b.split(","),f;for(f=0;f<e.length;f++){var g=e[f].match(/[-\+\d\.]+/g);if(g!=null){var i=parseFloat(g[0]),g=parseFloat(g[1]);c.push(i);d.push(g)}}this.setCoordinates(a,c,d)};
kaXmlFeature.prototype.setCoordinates=function(a,b,c){this.cxmax=this.cymin=this.cymax=this.cxmin=0;this.coords="";for(a=0;a<b.length;a++){var d=b[a],e=c[a];if(a==0||d<this.cxmin)this.cxmin=d;if(a==0||e>this.cymax)this.cymax=e;if(a==0||e<this.cymin)this.cymin=e;if(a==0||d>this.cxmax)this.cxmax=d}this.xn=[];this.yn=[];for(a=0;a<b.length;a++)d=(b[a]-this.cxmin)/this.mcs,e=(this.cymax-c[a])/this.mcs,a>0&&(this.coords+=","),this.coords+=Math.round(d)+","+Math.round(e),this.xn.push(d),this.yn.push(e)};
kaXmlFeature.prototype.rescale=function(){};function kaXmlLinestring(a){kaXmlFeature.apply(this,[a]);kaXmlLinestring.prototype.draw=_BrowserIdent_hasCanvasSupport()?kaXmlLinestring.prototype.draw_canvas:function(){};for(var b in kaXmlFeature.prototype)kaXmlLinestring.prototype[b]||(kaXmlLinestring.prototype[b]=kaXmlFeature.prototype[b])}
kaXmlLinestring.prototype.draw_canvas=function(a){if(a==null||this.xn==null)OpenLayers.Console.warn("kaXmlLinestring: point/coordinate is null",a,this);else{var b=a.xml_overlay.kaMap.geoToPix(this.cxmin,this.cymax),c=b[0],d=b[1],b=a.xml_overlay.kaMap.geoToPix(this.cxmax,this.cymin),e=b[0],f=b[1],b=a.xml_overlay.kaMap.geoToPix(a.div.lon,a.div.lat),g=b[0],i=b[1],b=a.xml_overlay.kaMap.getCurrentScale()/this.maxScale,e=e-c+10,f=f-d+10;if(!(e<=25&&f<=25)){if(this.canvas==null){this.ldiv=document.createElement("div");
this.ldiv.setAttribute("id",a.pid+"_trace");this.ldiv.style.position="absolute";if(_hidePointTrace[a.pid]||_hidePointTrace.ALL)this.ldiv.style.visibility="hidden";a.div.appendChild(this.ldiv);this.canvas=_BrowserIdent_newCanvas(this.ldiv)}this.ldiv.style.left=c-g-5+"px";this.ldiv.style.top=d-i-5+"px";_BrowserIdent_setCanvasHW(this.canvas,f,e);c=_BrowserIdent_getCanvasContext(this.canvas);c.save();c.clearRect(0,0,e,f);c.translate(5,5);c.strokeStyle="#"+this.color;c.globalAlpha=this.opacity;c.lineWidth=
this.stroke;c.beginPath();c.moveTo(this.xn[0]/b,this.yn[0]/b);for(d=1;d<this.xn.length;d++)c.lineTo(this.xn[d]/b,this.yn[d]/b);c.stroke();c.strokeStyle="#"+this.color2;c.beginPath();for(d=1;d<this.xn.length;d++)c.moveTo(this.xn[d]/b,this.yn[d]/b),c.arc(this.xn[d]/b,this.yn[d]/b,1,0,Math.PI*2,!1),g=document.createElement("div"),g.style.position="absolute",g.title=a.pid,g.className="trailPoint",this.ldiv.appendChild(g),g.style.left=this.xn[d]/b-4+"px",g.style.top=this.yn[d]/b-4+"px",g.style.width=g.style.height=
"14px",g.style.zIndex="1190",g._index=d,g.setAttribute("id",a.pid+"_"+d+"_trail"),g.onclick=function(b){return myTrailClicked(a.pid,b)};c.stroke();c.restore()}}};kaXmlLinestring.prototype.rescale=function(a){this.draw(a)};
function kaXmlPolygon(a){kaXmlFeature.apply(this,[a]);kaXmlPolygon.prototype.draw=_BrowserIdent_hasCanvasSupport()?kaXmlPolygon.prototype.draw_canvas:function(){};for(var b in kaXmlFeature.prototype)kaXmlPolygon.prototype[b]||(kaXmlPolygon.prototype[b]=kaXmlFeature.prototype[b])}
kaXmlPolygon.prototype.draw_canvas=function(a){var b=a.xml_overlay.kaMap.geoToPix(this.cxmin,this.cymax),c=b[0],d=b[1],b=a.xml_overlay.kaMap.geoToPix(this.cxmax,this.cymin),e=b[0],f=b[1],b=a.xml_overlay.kaMap.geoToPix(a.div.lon,a.div.lat),g=b[0],i=b[1],b=a.xml_overlay.kaMap.getCurrentScale()/this.maxScale,e=e-c+10,f=f-d+10;if(this.canvas==null)this.ldiv=document.createElement("div"),this.ldiv.style.position="absolute",a.div.appendChild(this.ldiv),this.canvas=_BrowserIdent_newCanvas(this.ldiv);this.ldiv.style.left=
c-g-5+"px";this.ldiv.style.top=d-i-5+"px";_BrowserIdent_setCanvasHW(this.canvas,f,e);a=_BrowserIdent_getCanvasContext(this.canvas);a.save();a.clearRect(0,0,e,f);a.translate(5,5);if(this.color!=null)a.fillStyle=this.color;if(this.bcolor!=null&&this.bcolor!="")a.strokeStyle=this.bcolor;a.globalAlpha=this.opacity;a.lineWidth=this.stroke;a.beginPath();a.moveTo(this.xn[0]/b,this.yn[0]/b);for(c=1;c<this.xn.length;c++)a.lineTo(this.xn[c]/b,this.yn[c]/b);this.color!=null&&a.fill();this.bcolor!=null&&this.bcolor!=
""&&a.stroke();a.restore()};function kaXmlLabel(){kaXmlGraphicElement.apply(this);for(var a in kaXmlGraphicElement.prototype)kaXmlLabel.prototype[a]||(kaXmlLabel.prototype[a]=kaXmlGraphicElement.prototype[a]);this.text="";this.color="black";this.boxcolor=null;this.w=64;this.h=24;this.yoff=this.xoff=0;this.fsize="10px";this.font="Arial";this.ltxt=this.ldiv=null;this.flash=!1;this.classn=null}kaXmlLabel.prototype.remove=function(){this.ltxt=this.ldiv=this.canvas=null};
kaXmlLabel.prototype.parseElement=function(a,b){if(b.firstChild!=null)this.text=b.firstChild.data;var c;c=b.getAttribute("color");if(c!=null)this.color=c;this.boxcolor=b.getAttribute("boxcolor");c=parseInt(b.getAttribute("w"));if(!isNaN(c))this.w=c;c=parseInt(b.getAttribute("h"));if(!isNaN(c))this.h=c;c=parseInt(b.getAttribute("px"));if(!isNaN(c))this.xoff=c;c=parseInt(b.getAttribute("py"));if(!isNaN(c))this.yoff=c;c=b.getAttribute("fsize");if(c!=null)this.fsize=c;c=b.getAttribute("font");if(c!=null)this.font=
c;c=b.getAttribute("flash");if(c!=null)this.flash=c;c=b.getAttribute("style");if(c!=null)this.classn=c};
kaXmlLabel.prototype.draw=function(){var a=this.xoff,b=this.yoff;this.ldiv=document.createElement("div");if(this.classn!=null)this.ldiv.className=this.classn;else{this.ldiv.style.fontFamily=this.font;this.ldiv.style.fontWeight="bold";this.ldiv.style.fontSize=this.fsize;this.ldiv.style.textAlign="center";this.ldiv.style.color=this.color;this.ldiv.style.left=a+"px";this.ldiv.style.top=b+"px";this.ldiv.style.paddingTop="1px";this.ldiv.style.paddingBottom="1px";this.ldiv.style.border="outset 1px";this.ldiv.style.position=
"absolute";this.ldiv.style.lineHeight="1.1em";if(this.flash)this.ldiv.style.textDecoration="blink",this.ldiv.style.border="solid 3px red";if(this.boxcolor!=null)this.ldiv.style.backgroundColor=this.boxcolor;this.ldiv.style.whiteSpace="nowrap"}this.ldiv.style.width="auto";this.ldiv.style.height="auto";this.ltxt=document.createTextNode(this.text);this.ldiv.appendChild(this.ltxt)};kaXmlLabel.prototype.rescale=function(){};
function kaXmlIcon(){kaXmlGraphicElement.apply(this);kaXmlIcon.prototype.draw=kaXmlIcon.prototype.draw_plain;for(var a in kaXmlGraphicElement.prototype)kaXmlIcon.prototype[a]||(kaXmlIcon.prototype[a]=kaXmlGraphicElement.prototype[a]);this.icon_src=null;this.rot=this.yoff=this.xoff=this.icon_h=this.icon_w=0;this.canvas=this.img=this.ldiv=null}kaXmlIcon.prototype.remove=function(){this.canvas=this.ldiv=null;if(this.img)this.img.onload=null;this.img=null};
kaXmlIcon.prototype.parseElement=function(a,b){this.icon_src=a.xml_overlay.urlNormalize(b.getAttribute("src"));this.icon_w=parseInt(b.getAttribute("w"));this.icon_h=parseInt(b.getAttribute("h"));var c;c=parseInt(b.getAttribute("px"));if(!isNaN(c))this.xoff=c;c=parseInt(b.getAttribute("py"));if(!isNaN(c))this.yoff=c;c=parseInt(b.getAttribute("rot"));if(!isNaN(c))this.rot=c};
kaXmlIcon.prototype.draw_canvas=function(a){var b=-this.icon_w/2+this.xoff,c=-this.icon_h/2+this.yoff;if(this.canvas==null)this.ldiv=document.createElement("div"),this.ldiv.style.position="absolute",this.ldiv.style.top=c+"px",this.ldiv.style.left=b+"px",a.div.appendChild(this.ldiv),this.canvas=_BrowserIdent_newCanvas(this.ldiv),_BrowserIdent_setCanvasHW(this.canvas,this.icon_h*2,this.icon_w*2);var d=_BrowserIdent_getCanvasContext(this.canvas);d.save();d.translate(-b,-c);d.rotate(this.rot*Math.PI/
180);this.img=new Image;this.img.src=this.icon_src;var e=this.img,f=this.icon_w,g=this.icon_h;this.img.onload=function(){d.drawImage(e,b,c,f,g);d.restore()}};
kaXmlIcon.prototype.draw_plain=function(){var a=-this.icon_w/2+this.xoff,b=-this.icon_h/2+this.yoff;this.ldiv=document.createElement("div");this.ldiv.style.position="absolute";this.ldiv.style.top=b+"px";this.ldiv.style.left=a+"px";this.img=document.createElement("img");this.img.src=this.icon_src;this.img.width=this.icon_w;this.img.height=this.icon_h;this.ldiv.appendChild(this.img)};
function kaXmlPoint(a,b){this.xml_overlay=b;this.pid=a;this.divId=this.xml_overlay.getDivId(a);this.geoy=this.geox=0;this.own=this.hasTrace=this.shown=!1;this.graphics=[];this.div=document.createElement("div");this.div.setAttribute("id",this.divId)}kaXmlPoint.prototype.placeOnMap=function(a,b){if(!this.shown)this.geox=a,this.geoy=b,this.showOnMap()};
kaXmlPoint.prototype.showOnMap=function(){if(!this.shown)this.xml_overlay.kaMap.addObjectGeo(this.xml_overlay.overlayCanvas,this.geox,this.geoy,this.div),this.shown=!0};kaXmlPoint.prototype.removeFromMap=function(){if(this.shown)this.xml_overlay.kaMap.removeObject(this.div),this.shown=!1;var a;for(a=0;a<this.graphics.length;a++)this.graphics[a].remove(this);this.graphics.splice(0);this.xml_overlay=this.div=null};
kaXmlPoint.prototype.setPosition=function(a,b){if(this.shown)this.geox=a,this.geoy=b,this.div.lat=b,this.div.lon=a};kaXmlPoint.prototype.addGraphic=function(a){this.graphics.push(a);a.draw(this)};kaXmlPoint.prototype.clear=function(){this.div.innerHTML="";this.graphics.length=0};kaXmlPoint.prototype.setInnerHtml=function(a){this.clear();this.div.innerHTML=a};kaXmlPoint.prototype.moveToFront=function(){this.div.style.zIndex=zzindex+20};var tstate=null;
kaXmlPoint.prototype.parse=function(a){var b,c=this.geox,d=this.geoy,e=parseFloat(a.getAttribute("x")),f=parseFloat(a.getAttribute("y")),g=a.getAttribute("href");b=a.getAttribute("title");var i=a.getAttribute("id"),h=i.substr(0,2)=="__",j=!1,k=!1;a.getAttribute("redraw")=="true"&&(j=!0);if(a.getAttribute("own")=="true")this.own=!0;k=trackedObject!=null&&i==trackedObject;if(this.shown){if(j&&this.clear(),this.setPosition(e,f),k&&(e!=c&&Math.abs(e-c)>50||f!=d&&Math.abs(f-d)>50)){myZoomToGeo(e,f);return}}else this.placeOnMap(e,
f),j=this.shown=!0;if(j){c=document.createElement("div");c.setAttribute("id",i+"_label");this.div.appendChild(c);c.style.position="absolute";c.style.zIndex=zzindex+10;h?c.style.zIndex=zzindex-10:_BrowserIdent_isMSIE()?(c.onmouseover=function(){this.parentNode.style.zIndex=zzindex+100},c.onmouseout=function(){this.parentNode.style.zIndex=zzindex}):(c.onmouseover=function(){this.style.zIndex=zzindex+100},c.onmouseout=function(){this.style.zIndex=zzindex});if(b!=null)c.title=b;c.onclick=function(a){return myObjectClicked(i,
a,g)};if(!h)c.oncontextmenu=function(a){showContextMenu(i,a);return!1},c.ontouchstart=function(a){tstate=a.touches[0];setTimeout(function(){tstate!=null&&(showContextMenu(i,tstate),tstate=null)},600);return!1},c.ontouchend=function(a){tstate!=null&&myObjectClicked(i,tstate,g);tstate=null;(a?a:event?event:null).cancelBubble=!0;return!1};h=a.getElementsByTagName("ihtml");for(b=0;b<h.length;b++)this.div.innerHTML=h[b].firstChild.nodeValue;this.hasTrace=!1;d=a.getElementsByTagName("linestring");for(b=
0;b<d.length;b++)h=new kaXmlLinestring(this),h.parseElement(this,d[b]),this.addGraphic(h),this.hasTrace=!0;d=a.getElementsByTagName("icon");for(b=0;b<d.length;b++)h=new kaXmlIcon,h.parseElement(this,d[b]),this.addGraphic(h),c.appendChild(h.ldiv);d=a.getElementsByTagName("polygon");for(b=0;b<d.length;b++)h=new kaXmlPolygon(this),h.parseElement(this,d[b]),this.addGraphic(h);d=a.getElementsByTagName("label");for(b=0;b<d.length;b++)if(h=new kaXmlLabel,h.parseElement(this,d[b]),this.addGraphic(h),c.appendChild(h.ldiv),
h.ldiv.setAttribute("id",i+"_label_txt"),_hidePointLabel[i]==!0)h.ldiv.style.visibility="hidden"}k&&setTracking(i)};kaXmlPoint.prototype.rescale=function(){var a;this.placeOnMap(this.geox,this.geoy);for(a=0;a<this.graphics.length;a++)this.graphics[a].rescale(this)};var _BrowserIdent_browser=null,_BrowserIdent_version=null,_BrowserIdent_place=0,_BrowserIdent_thestring=null,_BrowserIdent_detect=null,_BrowserIdent_isIE=!1;
function _BrowserIdent(){_BrowserIdent_detect=navigator.userAgent.toLowerCase();_BrowserIdent_checkIt("konqueror")?_BrowserIdent_browser="Konqueror":_BrowserIdent_checkIt("safari")?_BrowserIdent_browser="Safari":_BrowserIdent_checkIt("omniweb")?_BrowserIdent_browser="OmniWeb":_BrowserIdent_checkIt("opera")?_BrowserIdent_browser="Opera":_BrowserIdent_checkIt("webtv")?_BrowserIdent_browser="WebTV":_BrowserIdent_checkIt("icab")?_BrowserIdent_browser="iCab":_BrowserIdent_checkIt("msie")?_BrowserIdent_browser=
"Internet Explorer":_BrowserIdent_checkIt("firefox")?_BrowserIdent_browser="Firefox":_BrowserIdent_checkIt("iceweasel")?_BrowserIdent_browser="Firefox":_BrowserIdent_checkIt("compatible")?_BrowserIdent_browser="An unknown browser":(_BrowserIdent_browser="Netscape Navigator",_BrowserIdent_version=_BrowserIdent_detect.charAt(8));_BrowserIdent_version||(_BrowserIdent_version=_BrowserIdent_detect.charAt(_BrowserIdent_place+_BrowserIdent_thestring.length));_BrowserIdent_isMSIE()&&safeParseInt(_BrowserIdent_version)<=
7&&alert("OBS: Vi st\u00f8tter ikke lenger Internet Explorer versjon 7 eller eldre. Anbefaler oppgradering av nettleser")}function _BrowserIdent_isMSIE(){return _BrowserIdent_browser=="Internet Explorer"}function _BrowserIdent_isOpera(){return _BrowserIdent_browser=="Opera"}function _BrowserIdent_checkIt(a){_BrowserIdent_place=_BrowserIdent_detect.indexOf(a)+1;_BrowserIdent_thestring=a;return _BrowserIdent_place}
function _BrowserIdent_setOpacity(a,b){if(b==void 0||b>=1)return"";if(_BrowserIdent_browser=="Netscape Navigator")a.style.MozOpacity=b;else{if(_BrowserIdent_browser=="Internet Explorer"&&parseInt(this.version)>=4)var c=a.style.cssText,c="filter: alpha(opacity="+b*100+");"+c;else c=a.style.cssText,c="opacity: "+b+";"+c;a.style.cssText=c}}
function _BrowserIdent_getPreferredImageType(){return _BrowserIdent_browser=="Netscape Navigator"?"P":_BrowserIdent_browser=="Opera"?"P":_BrowserIdent_browser=="Firefox"?"P":_BrowserIdent_browser=="Safari"?"P":_BrowserIdent_browser=="Konqueror"?"P":"G"}function _BrowserIdent_getPreferredOpacity(){return _BrowserIdent_browser=="Netscape Navigator"?"server":_BrowserIdent_browser=="Firefox"?"server":_BrowserIdent_browser=="Opera"?"server":_BrowserIdent_browser=="Konqueror"?"server":"client"}
var xmlOverlayUseCanvas=!0;function _BrowserIdent_hasCanvasSupport(){return!xmlOverlayUseCanvas?!1:_BrowserIdent_browser=="Internet Explorer"?!0:_BrowserIdent_browser=="Firefox"?!0:_BrowserIdent_browser=="Safari"?!0:_BrowserIdent_browser=="Opera"?!0:!1}function _BrowserIdent_newCanvas(a){var b=document.createElement("canvas");a.appendChild(b);typeof G_vmlCanvasManager!="undefined"&&(b=G_vmlCanvasManager.initElement(b));return b}
function _BrowserIdent_getCanvasContext(a){return _BrowserIdent_hasCanvasSupport()?a.getContext("2d"):null}function _BrowserIdent_setCanvasHW(a,b,c){a.width=c;a.height=b}_BrowserIdent();
