#!/bin/bash
set -e



case "$1" in
    configure|reconfigure)
        if [ -e "/etc/cron.daily/polaric-webapp.dpkg-old" ]; then
           rm -R /etc/cron.daily/polaric-webapp.dpkg-old
        fi 
        
        if [ -e "/var/www/aprs/img" ]; then
           rm -R /var/www/aprs/img
        fi
        ln -s /var/www/aprs/OpenLayers/img /var/www/aprs/img
        
        if [ -e "/var/www/aprs/theme" ]; then
           rm -R /var/www/aprs/theme
        fi
        ln -s /var/www/aprs/OpenLayers/theme /var/www/aprs/theme
        
        if [ -d "/var/www/html" ]; then 
            if [ -d "/var/www/html/aprs" ]; then
               rm /var/www/html/aprs
            fi
            ln -s /var/www/aprs /var/www/html/aprs
        fi
        
        a2enmod proxy_http > /dev/null 2>&1
        a2enmod expires > /dev/null 2>&1
        a2enmod deflate > /dev/null 2>&1
        a2ensite aprs.conf > /dev/null 2>&1 
        chown www-data:www-data /var/lib/polaric/mapcache
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "$0 called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#
