#!/bin/sh
set -e
INIFILE=/etc/polaric-aprsd/server.ini

# Source debconf library.
. /usr/share/debconf/confmodule


case "$1" in
    configure|reconfigure)
        if [ -e "/var/www/aprs/KaMap/mapserv" ]; then
           rm -R /var/www/aprs/KaMap/mapserv
        fi
        ln -s /etc/polaric-webapp/mapserv /var/www/aprs/KaMap/mapserv
        a2enmod proxy_http > /dev/null 2>&1
        a2enmod expires > /dev/null 2>&1
        a2ensite aprs > /dev/null 2>&1
        chown www-data:www-data /var/www/aprs/kacache2
        db_stop
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "$0 called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#
