#!/bin/bash
set -e


case "$1" in
    install)
        ;;

    upgrade)
        if [ -d "/etc/polaric-webapp/mapserv" ]; then
           rm -R /etc/polaric-webapp/mapserv
        fi
        if [ -d "/var/www/aprs/kacache2" ]; then
           echo "Removing old kamap cache..."
           rm -R /var/www/aprs/kacache2
        fi
        ;;
        
    abort-upgrade)
        ;;

    *)
        echo "preinst called with unknown argument \`$1'" >&2
        exit 0
        ;;
esac

#DEBHELPER#

exit 0
