var isCSS,isW3C,isIE4,isNN4;function initDHTMLAPI(){document.images&&(isW3C=(isCSS=document.body&&document.body.style?!0:!1)&&document.getElementById?!0:!1,isIE4=isCSS&&document.all?!0:!1,isNN4=document.layers?!0:!1,isIE6CSS=document.compatMode&&document.compatMode.indexOf("CSS1")>=0?!0:!1)}function seekLayer(b,c){for(var d,e=0;e<b.layers.length;e++){if(b.layers[e].name==c){d=b.layers[e];break}b.layers[e].document.layers.length>0&&(d=seekLayer(document.layers[e].document,c))}return d}
function getRawObject(b){var c;typeof b=="string"?isW3C?c=document.getElementById(b):isIE4?c=document.all(b):isNN4&&(c=seekLayer(document,b)):c=b;return c}function getObject(b){if((b=getRawObject(b))&&isCSS)b=b.style;return b}function shiftTo(b,c,d){if(b=getObject(b))if(isCSS){var e=typeof b.left=="string"?"px":0;b.left=c+e;b.top=d+e}else isNN4&&b.moveTo(c,d)}
function shiftBy(b,c,d){var e=getObject(b);if(e)if(isCSS){var f=typeof e.left=="string"?"px":0;e.left=getObjectLeft(b)+c+f;e.top=getObjectTop(b)+d+f}else isNN4&&e.moveBy(c,d)}function setZIndex(b,c){var d=getObject(b);if(d)d.zIndex=c}function setBGColor(b,c){var d=getObject(b);if(d)if(isNN4)d.bgColor=c;else if(isCSS)d.backgroundColor=c}function show(b){if(b=getObject(b))b.visibility="visible"}function hide(b){if(b=getObject(b))b.visibility="hidden"}
function getObjectLeft(b){var b=getRawObject(b),c=0;if(document.defaultView)c=document.defaultView.getComputedStyle(b,"").getPropertyValue("left");else if(b.currentStyle)c=b.currentStyle.left;else if(b.style)c=b.style.left;else if(isNN4)c=b.left;return parseInt(c)}
function getObjectTop(b){var b=getRawObject(b),c=0;if(document.defaultView)c=document.defaultView.getComputedStyle(b,"").getPropertyValue("top");else if(b.currentStyle)c=b.currentStyle.top;else if(b.style)c=b.style.top;else if(isNN4)c=b.top;return parseInt(c)}function getObjectWidth(b){var b=getRawObject(b),c=0;if(b.offsetWidth)c=b.offsetWidth;else if(b.clip&&b.clip.width)c=b.clip.width;else if(b.style&&b.style.pixelWidth)c=b.style.pixelWidth;return parseInt(c)}
function getObjectHeight(b){var b=getRawObject(b),c=0;if(b.offsetHeight)c=b.offsetHeight;else if(b.clip&&b.clip.height)c=b.clip.height;else if(b.style&&b.style.pixelHeight)c=b.style.pixelHeight;return parseInt(c)}function getInsideWindowWidth(){if(window.innerWidth)return window.innerWidth;else if(isIE6CSS)return document.body.parentElement.clientWidth;else if(document.body&&document.body.clientWidth)return document.body.clientWidth;return 0}
function getInsideWindowHeight(){if(window.innerHeight)return window.innerHeight;else if(isIE6CSS)return document.body.parentElement.clientHeight;else if(document.body&&document.body.clientHeight)return document.body.clientHeight;return 0};var aXmlHttp=[],aXmlResponse=[];function xmlResult(){for(var b=0;b<aXmlHttp.length;b++)if(aXmlHttp[b]&&aXmlHttp[b][0]&&aXmlHttp[b][0].readyState==4){var c=aXmlHttp[b][3],d=aXmlHttp[b][2],e=aXmlHttp[b][1],f=aXmlHttp[b][0].responseText,g=aXmlHttp[b][0].status;aXmlHttp[b][0]=null;aXmlHttp[b][1]=null;aXmlHttp[b]=null;g==200?d.apply(e,Array(f)):(OpenLayers.Console.info("xmlResult: status",g),g==503?setTimeout(function(){window.location.reload()},25E3):g==0&&setTimeout(function(){call(c,e,d)},1E3))}}
function abortCall(b){aXmlHttp[b]!=null&&aXmlHttp[b][0]!=null&&aXmlHttp[b][0].abort()}
function call(b,c,d){var e="GET",f="";arguments.length==4&&(e="POST",f=b.split(/\?/),b=f[0],f=f[1],f==null&&(f="empty"));for(var g=aXmlHttp.length,k=0;k<g;k++)if(aXmlHttp[k]==null){g=k;break}aXmlHttp[g]=Array(2);aXmlHttp[g][0]=getXMLHTTP();aXmlHttp[g][1]=c;aXmlHttp[g][2]=d;aXmlHttp[g][3]=b;if(aXmlHttp[g])aXmlHttp[g][0].open(e,b,!0),aXmlHttp[g][0].onreadystatechange=xmlResult,e=="POST"?(aXmlHttp[g][0].setRequestHeader("Content-Type","application/x-www-form-urlencoded"),aXmlHttp[g][0].send(f)):e=="GET"&&
aXmlHttp[g][0].send(null);return g}function getXMLHTTP(){var b=null;!b&&typeof XMLHttpRequest!="undefined"&&(b=new XMLHttpRequest);if(!b)try{b=new ActiveXObject("Msxml2.XMLHTTP")}catch(c){try{b=new ActiveXObject("Microsoft.XMLHTTP")}catch(d){b=null}}return b};var gnLastEventId=0,KAMAP_ERROR=gnLastEventId++,KAMAP_WARNING=gnLastEventId++,KAMAP_NOTICE=gnLastEventId++,KAMAP_INITIALIZED=gnLastEventId++,KAMAP_MAP_INITIALIZED=gnLastEventId++,KAMAP_EXTENTS_CHANGED=gnLastEventId++,KAMAP_SCALE_CHANGED=gnLastEventId++,KAMAP_LAYERS_CHANGED=gnLastEventId++,KAMAP_LAYER_STATUS_CHANGED=gnLastEventId++,KAMAP_CONTEXT_MENU=gnLastEventId++,KAMAP_METAEXTENTS_CHANGED=gnLastEventId++,KAMAP_MAP_CLICKED=gnLastEventId++,KAMAP_MOVE_START=gnLastEventId++,KAMAP_MOVE_END=gnLastEventId++;
function kaMap(b){this.isIE6CSS=this.isNN4=this.isIE4=this.isW3C=this.isCSS=!1;if(document.images)this.isW3C=(this.isCSS=document.body&&document.body.style?!0:!1)&&document.getElementById?!0:!1,this.isIE4=this.isCSS&&document.all?!0:!1,this.isNN4=document.layers?!0:!1,this.isIE6CSS=document.compatMode&&document.compatMode.indexOf("CSS1")>=0?!0:!1;this.domObj=this.getRawObject(b);this.domObj.style.overflow="hidden";this.loadUnchecked=this.hideLayersOnMove=!1;this.initializationState=0;this.bMouseDown=
!1;this.lasty=this.lastx=0;this.theInsideLayer=null;this.viewportWidth=this.getObjectWidth(this.domObj);this.viewportHeight=this.getObjectHeight(this.domObj);this.yOffset=this.xOffset=0;this.currentMap="";this.nCurrentLeft=this.nCurrentTop=this.nHigh=this.nWide=0;this.aMaps=[];this.cellSize=null;this.eventManager=new _eventManager;this.as=slideid=null;this.accelerationFactor=1;this.pixelsPerStep=30;this.timePerStep=25;this.server=this.server=server_url?server_url:"";this.init="KaMap/init.php";this.tileURL=
null;this.aObjects=[];this.aCanvases=[];this.layersHidden=!1;this.aTools=[];this.aInfoTools=[];for(b=0;b<gnLastEventId;b++)this.registerEventID(b);this.createLayers()}kaMap.prototype.getMapProjection=function(){return this.olMap.getProjectionObject()};kaMap.prototype.getResolution=function(){return this.olMap.getResolution()};
kaMap.prototype.seekLayer=function(b,c){for(var d,e=0;e<b.layers.length;e++){if(b.layers[e].name==c){d=b.layers[e];break}b.layers[e].document.layers.length>0&&(d=this.seekLayer(document.layers[e].document,c))}return d};
kaMap.prototype.initialize=function(){if(this.initializationState==2)return this.triggerEvent(KAMAP_ERROR,"ERROR: ka-Map! is already initialized!"),!1;else if(this.intializationState==1)return this.triggerEvent(KAMAP_WARNING,"WARNING: ka-Map! is currently initializing ... wait for the KAMAP_INITIALIZED event to be triggered."),!1;this.initializationState=1;var b=this.server+this.init,c=this.init.indexOf("?")==-1?"?":"&";arguments.length>0&&arguments[0]!=""&&(b=b+c+"map="+arguments[0],c="&");arguments.length>
1&&arguments[1]!=""&&(b=b+c+"extents="+arguments[1],c="&");arguments.length>2&&arguments[2]!=""&&(b=b+c+"centerPoint="+arguments[2]);call(b,this,this.initializeCallback);return!0};
kaMap.prototype.initializeCallback=function(b){if(b.substr(0,1)!="/")return this.triggerEvent(KAMAP_ERROR,"ERROR: ka-Map! initialization failed on the server.  Message returned was:\n"+b),!1;this.olMap=new OpenLayers.Map(mapOptions);this.utmProjection=utm_projection;kaMapFirst&&eval(b);baseLayers!=null&&baseLayers.length>0&&this.olMap.addLayers(baseLayers);kaMapFirst||eval(b);this.olMap.events.register("zoomend",this,function(){this.triggerEvent(KAMAP_SCALE_CHANGED,this.getCurrentScale());this.triggerEvent(KAMAP_EXTENTS_CHANGED,
this.getGeoExtents())});this.olMap.events.register("moveend",this,function(){mousetrack_suspend=!1;this.triggerEvent(KAMAP_EXTENTS_CHANGED,this.getGeoExtents());this.triggerEvent(KAMAP_MOVE_END)});this.olMap.events.register("movestart",this,function(){mousetrack_suspend=!0;this.triggerEvent(KAMAP_MOVE_START)});isMobile||this.olMap.addControl(new OpenLayers.Control.PanZoomBar);this.olMap.addControl(new OpenLayers.Control.LayerSwitcher);this.plink=new OpenLayers.Control.Permalink;this.plink.setMap(this.olMap);
for(b=0;b<mapViews.length;b++){var c=new View(mapViews[b]);this.aMaps[c.name]=c}this.triggerEvent(KAMAP_MAP_INITIALIZED);this.olMap.render(this.domObj);document.getElementById("permolink").appendChild(this.plink.draw());this.plink.element.innerHTML="link to this view";this.setBackgroundColor(backgroundColor);this.triggerEvent(KAMAP_INITIALIZED);this.triggerEvent(KAMAP_SCALE_CHANGED,this.getCurrentScale());this.initializationState=2};
kaMap.prototype.setBackgroundColor=function(b){this.domObj.style.backgroundColor=b;return!0};function touchHandler(b){var c=b.changedTouches[0],d="";switch(b.type){case "touchstart":d="mousedown";break;case "touchmove":d="mousemove";break;case "touchend":d="mouseup";break;default:return}var e=document.createEvent("MouseEvent");e.initMouseEvent(d,!0,!0,window,1,c.screenX,c.screenY,c.clientX,c.clientY,!1,!1,!1,!1,0,null);c.target.dispatchEvent(e);b.preventDefault()}
kaMap.prototype.createLayers=function(){this.theInsideLayer=document.createElement("div");this.theInsideLayer.id="theInsideLayer";this.theInsideLayer.style.position="absolute";this.theInsideLayer.style.left="0px";this.theInsideLayer.style.top="0px";this.theInsideLayer.style.zIndex="750";this.theInsideLayer.kaMap=this;if(this.currentTool)this.theInsideLayer.style.cursor=this.currentTool.cursor;this.domObj.appendChild(this.theInsideLayer);this.domObj.kaMap=this;this.theInsideLayer.onclick=kaMap_onclick;
this.theInsideLayer.onmousedown=kaMap_onmousedown;this.theInsideLayer.onmouseup=kaMap_onmouseup;this.theInsideLayer.onmousemove=kaMap_onmousemove;this.theInsideLayer.onmouseover=kaMap_onmouseover;this.domObj.onmouseout=kaMap_onmouseout;this.theInsideLayer.onkeypress=kaMap_onkeypress;this.theInsideLayer.ondblclick=kaMap_ondblclick;this.theInsideLayer.oncontextmenu=kaMap_oncontextmenu;this.theInsideLayer.onmousewheel=kaMap_onmousewheel;this.theInsideLayer.ontouchstart=touchHandler;this.theInsideLayer.ontouchmove=
touchHandler;this.theInsideLayer.ontouchend=touchHandler;this.theInsideLayer.ontouchcancel=touchHandler;window.addEventListener&&this.domObj.addEventListener("DOMMouseScroll",kaMap_onmousewheel,!1);this.theInsideLayer.ondragstart=new Function([],"var e=e?e:event;e.cancelBubble=true;e.returnValue=false;return false;");this.olMap=null};kaMap.prototype.showLayers=function(){};kaMap.prototype.hideLayers=function(){};kaMap.prototype.getPlink=function(){return this.plink};
kaMap.prototype.getRawObject=function(b){var c;typeof b=="string"?this.isW3C?c=document.getElementById(b):this.isIE4?c=document.all(b):this.isNN4&&(c=seekLayer(document,b)):c=b;return c};kaMap.prototype.getObject=function(b){if((b=this.getRawObject(b))&&this.isCSS)b=b.style;return b};kaMap.prototype.getObjectWidth=function(b){var b=this.getRawObject(b),c=0;if(b.offsetWidth)c=b.offsetWidth;else if(b.clip&&b.clip.width)c=b.clip.width;else if(b.style&&b.style.pixelWidth)c=b.style.pixelWidth;return parseInt(c)};
kaMap.prototype.getObjectHeight=function(b){var b=this.getRawObject(b),c=0;if(b.offsetHeight)c=b.offsetHeight;else if(b.clip&&b.clip.height)c=b.clip.height;else if(b.style&&b.style.pixelHeight)c=b.style.pixelHeight;return parseInt(c)};kaMap.prototype.zoomTo=function(b,c){var d=new OpenLayers.LonLat(b,c);d.transform(this.utmProjection,this.getMapProjection());this.olMap.setCenter(d)};
kaMap.prototype.zoomToExtents=function(b,c,d,e){b=new OpenLayers.Bounds(b,c,d,e);b.transform(this.utmProjection,this.getMapProjection());this.olMap.zoomToExtent(b,!0)};
kaMap.prototype.createDrawingCanvas=function(b,c){var d=document.createElement("div");d.style.position="absolute";d.id="canvas";d.style.left="0px";d.style.top="0px";d.style.width="3000px";d.style.height="3000px";d.style.zIndex=b;this.theInsideLayer.appendChild(d);if(c){var e=document.createElement("div");e.id="canvasBG";e.style.marginLeft="-50%";e.style.marginTop="-50%";e.style.width="150%";e.style.height="150%";d.appendChild(e)}this.aCanvases.push(d);d.kaMap=this;return d};
kaMap.prototype.updateDrawingCanvas=function(b){this.theInsideLayer.removeChild(b);this.theInsideLayer.appendChild(b)};kaMap.prototype.removeDrawingCanvas=function(b){for(var c=0;c<this.aCanvases.length;c++)this.aCanvases[c]==b&&this.aCanvases.splice(c,1);this.theInsideLayer.removeChild(b);b.kaMap=null;return!0};kaMap.prototype.addObjectGeo=function(b,c,d,e){e.lon=c;e.lat=d;e.style.position="absolute";e.canvas=b;b.appendChild(e);this.aObjects.push(e)};
kaMap.prototype.removeObject=function(b){if(b==null){for(var c=0;c<this.aObjects.length;c++)b=this.aObjects[c],b.canvas&&b.canvas.removeChild(b);this.aObjects=[];return!0}else{for(c=0;c<this.aObjects.length;c++)if(this.aObjects[c]==b){b=this.aObjects[c];if(b.canvas)b.canvas.removeChild(b),b.canvas=null;this.aObjects.splice(c,1);return!0}return!1}};
kaMap.prototype.removeAllObjects=function(b){for(var c=0;c<this.aObjects.length;c++)if(obj=this.aObjects[c],obj.canvas&&obj.canvas==b)obj.canvas.removeChild(obj),obj.canvas=null,this.aObjects.splice(c--,1);return!0};
kaMap.prototype.centerObject=function(b){var c=-safeParseInt(this.theInsideLayer.style.left)+this.viewportWidth/2,d=-safeParseInt(this.theInsideLayer.style.top)+this.viewportHeight/2,e=b.xOffset?b.xOffset:0,f=b.yOffset?b.yOffset:0,c=safeParseInt(b.style.left)-e-c,b=safeParseInt(b.style.top)-f-d;this.slideBy(-c,-b);return!0};
kaMap.prototype.updateObjects=function(){document.getElementById("OpenLayers.Map_14_OpenLayers_ViewPort");document.getElementById("canvas");for(var b=0;b<this.aObjects.length;b++){var c=this.aObjects[b],d=c.xOffset?c.xOffset:0,e=c.yOffset?c.yOffset:0,f=this.geoToPix(c.lon,c.lat),d=f[0]+d;c.style.top=f[1]+e+"px";c.style.left=d+"px"}};
kaMap.prototype.geoToPix=function(b,c){var d=new OpenLayers.LonLat(b,c),d=d.transform(this.utmProjection,this.getMapProjection()),d=this.olMap.getPixelFromLonLat(d);return[Math.floor(d.x),Math.floor(d.y)]};kaMap.prototype.pixToGeo=function(b,c){arguments.length==3&&arguments[2]&&(b+=this.xOrigin,c+=this.yOrigin);var d=this.olMap.getLonLatFromPixel(new OpenLayers.Pixel(b,c)),d=d.transform(this.getMapProjection(),this.utmProjection);return[d.lon,d.lat]};
kaMap.prototype.resize=function(){this.olMap&&(this.olMap.updateSize(),this.triggerEvent(KAMAP_EXTENTS_CHANGED,this.getGeoExtents()))};kaMap_onkeypress=function(b){if(this.kaMap.currentTool)this.kaMap.currentTool.onkeypress(b);if(this.kaMap.aInfoTools.length>0)for(var c=0;c<this.kaMap.aInfoTools.length;c++)this.kaMap.aInfoTools[c].onkeypress(b)};
kaMap_onmousemove=function(b){b=b?b:event?event:null;b.button==2&&this.kaMap.triggerEvent(KAMAP_CONTEXT_MENU);if(this.kaMap.currentTool)this.kaMap.currentTool.onmousemove(b);if(this.kaMap.aInfoTools.length>0)for(var c=0;c<this.kaMap.aInfoTools.length;c++)this.kaMap.aInfoTools[c].onmousemove(b)};kaMap_onmousedown=function(b){if(this.kaMap.currentTool)this.kaMap.currentTool.onmousedown(b);if(this.kaMap.aInfoTools.length>0)for(var c=0;c<this.kaMap.aInfoTools.length;c++)this.kaMap.aInfoTools[c].onmousedown(b)};
kaMap_onmouseup=function(b){if(this.kaMap.currentTool)this.kaMap.currentTool.onmouseup(b);if(this.kaMap.aInfoTools.length>0)for(var c=0;c<this.kaMap.aInfoTools.length;c++)this.kaMap.aInfoTools[c].onmouseup(b)};kaMap_onmouseover=function(b){if(this.kaMap.currentTool)this.kaMap.currentTool.onmouseover(b);if(this.kaMap.aInfoTools.length>0)for(var c=0;c<this.kaMap.aInfoTools.length;c++)this.kaMap.aInfoTools[c].onmouseover(b)};
kaMap_onmouseout=function(b){if(this.kaMap.currentTool)this.kaMap.currentTool.onmouseout(b);if(this.kaMap.aInfoTools.length>0)for(var c=0;c<this.kaMap.aInfoTools.length;c++)this.kaMap.aInfoTools[c].onmouseout(b)};kaMap_oncontextmenu=function(b){b=b?b:event;b.preventDefault&&b.preventDefault();return!1};kaMap_onclick=function(b){if(this.kaMap.currentTool)this.kaMap.currentTool.onclick(b?b:event)};
kaMap_ondblclick=function(b){if(this.kaMap.currentTool)this.kaMap.currentTool.ondblclick(b);if(this.kaMap.aInfoTools.length>0)for(var c=0;c<this.kaMap.aInfoTools.length;c++)this.kaMap.aInfoTools[c].ondblclick(b)};kaMap_onmousewheel=function(b){if(this.kaMap.currentTool)this.kaMap.currentTool.onmousewheel(b)};kaMap.prototype.cancelEvent=function(b){b=b?b:event?event:null;b.returnValue=!1;b.preventDefault&&b.preventDefault();return!1};kaMap.prototype.registerTool=function(b){this.aTools.push(b)};
kaMap.prototype.activateTool=function(b){b.isInfoTool()?this.aInfoTools.push(b):(this.currentTool&&this.currentTool.deactivate(),this.currentTool=b,this.theInsideLayer&&this.setCursor(this.currentTool.cursor))};kaMap.prototype.deactivateTool=function(b){if(b.isInfoTool())for(var c=0;c<this.aInfoTools.length;c++){if(this.aInfoTools[c]==b){this.aInfoTools.splice(c,1);break}}else{if(this.currentTool==b)this.currentTool=null;if(this.theInsideLayer)this.theInsideLayer.style.cursor="auto"}};
kaMap.prototype.setCursor=function(b){if(b&&b.length&&typeof b=="object")for(var c=0;c<b.length;c++){if(this.theInsideLayer.style.cursor=b[c],this.theInsideLayer.style.cursor==b[c])break}else this.theInsideLayer.style.cursor=typeof b=="string"?b:"auto"};
kaMap.prototype.addMap=function(b){if(use_kaMap_maps){OpenLayers.Console.info("addMap: ",b.name);b.kaMap=this;getViewsFromKaMap&&(this.aMaps[b.name]=new View(b.name,b.title,b.defaultExtents));for(var c,d,e=0;e<b.aLayers.length;++e){c=b.aLayers[e];d=[];for(var f=0;f<b.aScales.length;++f)c.scales[f]=="1"&&d.push(b.aScales[f]);c=new OpenLayers.Layer.KaMap(b.title+" (ka-map)","KaMap/tile.php",{i:c.imageformat,g:c.name,map:b.name},{scales:d});this.olMap.addLayer(c)}}};kaMap.prototype.getMaps=function(){return this.aMaps};
kaMap.prototype.getCurrentMap=function(){return this.aMaps[this.currentMap]};kaMap.prototype.selectMap=function(b,c){OpenLayers.Console.info("selectMap: "+b);if(this.aMaps[b]){this.currentMap=b;if(!c){var d=this.aMaps[b];this.zoomToExtents(d.extent[0],d.extent[1],d.extent[2],d.extent[3])}return!0}else return OpenLayers.Console.warn("Map view not found: "+b),!1};kaMap.prototype.getBaseLayer=function(){return this.olMap.baseLayer.id};
kaMap.prototype.setBaseLayer=function(b){b=this.olMap.getLayer(b);b!=null&&this.olMap.setBaseLayer(b)};kaMap.prototype.getMaxScale=function(){return 5E3};kaMap.prototype.getUnits=function(){return this.olMap.getUnits()};kaMap.prototype.getGeoExtents=function(){var b=this.olMap.getExtent();if(b!=null)return b.toArray();OpenLayers.Console.warn("getGeoExtents: extent is null");return[0,0,0,0]};kaMap.prototype.zoomIn=function(){this.olMap.zoomIn()};kaMap.prototype.zoomOut=function(){this.olMap.zoomOut()};
kaMap.prototype.zoomToScale=function(b){this.olMap.zoomToScale(b)};kaMap.prototype.zoomByFactor=function(){throw"zoomByFactor not implemented";};kaMap.prototype.getCurrentScale=function(){return this.olMap==null?null:this.olMap.getScale()};kaMap.prototype.setLayerQueryable=function(b,c){this.aMaps[this.currentMap].setLayerQueryable(b,c)};kaMap.prototype.registerEventID=function(b){return this.eventManager.registerEventID(b)};
kaMap.prototype.registerForEvent=function(b,c,d){return this.eventManager.registerForEvent(b,c,d)};kaMap.prototype.deregisterForEvent=function(b,c,d){return this.eventManager.deregisterForEvent(b,c,d)};kaMap.prototype.triggerEvent=function(b){return this.eventManager.triggerEvent.apply(this.eventManager,arguments)};function safeParseInt(b){return Math.round(parseFloat(b))}
function View(b){this.name=typeof b.name!="undefined"?b.name:"noname";this.title=typeof b.title!="undefined"?b.title:"no title";this.extent=typeof b.extent!="undefined"?b.extent:[]}
function _map(b){this.aLayers=[];this.aZoomTo=[];this.kaMap=null;this.name=typeof b.name!="undefined"?b.name:"noname";this.title=typeof b.title!="undefined"?b.title:"no title";this.aScales=typeof b.scales!="undefined"?b.scales:[1];this.currentScale=typeof b.currentScale!="undefined"?parseFloat(b.currentScale):0;this.units=typeof b.units!="undefined"?b.units:5;this.resolution=typeof b.resolution!="undefined"?b.resolution:72;this.defaultExtents=typeof b.defaultExtents!="undefined"?b.defaultExtents:
[];this.currentExtents=typeof b.currentExtents!="undefined"?b.currentExtents:[];this.maxExtents=typeof b.maxExtents!="undefined"?b.maxExtents:[];this.backgroundColor=typeof b.backgroundColor!="undefined"?b.backgroundColor:"#ffffff";this.version=typeof b.version!="undefined"?b.version:""}_map.prototype.addLayer=function(b){b._map=this;b.zIndex=this.aLayers.length;this.aLayers.push(b)};
_map.prototype.removeLayer=function(b){var c=[];for(i=0,a=0;i<this.aLayers.length;i++)this.aLayers[i]!=b&&(c[a]=this.aLayers[i],a++);this.aLayers=c;return!0};_map.prototype.getQueryableLayers=function(){for(var b=[],c=this.getLayers(),d=0;d<c.length;d++)c[d].isQueryable()&&b.push(c[d]);return b};_map.prototype.getLayers=function(){for(var b=[],c=0;c<this.aLayers.length;c++)this.aLayers[c].isVisible()&&(this.aLayers[c].visible||this.kaMap.loadUnchecked)&&b.push(this.aLayers[c]);return b};
_map.prototype.getAllQueryableLayers=function(){for(var b=[],c=0;c<this.aLayers.length;c++)this.aLayers[c].isQueryable()&&b.push(this.aLayers[c]);return b};_map.prototype.getAllLayers=function(){return this.aLayers};_map.prototype.getLayer=function(b){for(var c=0;c<this.aLayers.length;c++)if(this.aLayers[c].name==b)return this.aLayers[c]};_map.prototype.getScales=function(){return this.aScales};_map.prototype.setLayerQueryable=function(b,c){var d=this.getLayer(b);typeof d!="undefined"&&d.setQueryable(c)};
_map.prototype.setDefaultExtents=function(b,c,d,e){this.defaultExtents=[b,c,d,e];this.currentExtents.length==0&&this.setCurrentExtents(b,c,d,e)};_map.prototype.setCurrentExtents=function(b,c,d,e){this.currentExtents=[b,c,d,e]};_map.prototype.setMaxExtents=function(b,c,d,e){this.maxExtents=[b,c,d,e]};_map.prototype.setBackgroundColor=function(b){this.backgroundColor=b};
function _layer(b){this._map=this.domObj=null;this.name=typeof b.name!="undefined"?b.name:"unnamed";this.queryable=typeof b.queryable!="undefined"?b.queryable:!1;this.queryState=typeof b.queryable!="undefined"?b.queryable:!1;this.tileSource=typeof b.tileSource!="undefined"?b.tileSource:"auto";this.scales=typeof b.scales!="undefined"?b.scales:[1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1];this.toLoad=0}_layer.prototype.isQueryable=function(){return this.queryState};
_layer.prototype.setQueryable=function(b){if(this.queryable)this.queryState=b};_layer.prototype.setZIndex=function(b){this.zIndex=b;if(this.domObj)this.domObj.style.zIndex=b};function _eventManager(){this.events=[];this.lastEventID=0}_eventManager.prototype.registerEventID=function(b){new String(b);this.events[b]||(this.events[b]=[])};_eventManager.prototype.registerForEvent=function(b,c,d){new String(b);this.events[b].push([c,d])};
_eventManager.prototype.deregisterForEvent=function(b,c,d){new String(b);var e=!1;if(!this.events[b])return!1;for(var f=0;f<this.events[b].length;f++)this.events[b][f][0]==c&&this.events[b][f][1]==d&&(this.events[b].splice(f,1),e=!0);return e};_eventManager.prototype.triggerEvent=function(b){new String(b);if(!this.events[b])return!1;for(c=1;c<arguments.length;c++);for(var c=0;c<this.events[b].length;c++)this.events[b][c][1].apply(this.events[b][c][0],arguments);return!0};var goQueueManager=new _queueManager;
function _queueManager(){this.queue=[]}_queueManager.prototype.enqueue=function(b,c,d,e){for(var f=this.queue.length,g=0;g<this.queue.length;g++)if(this.queue[g]==null){f=g;break}b=window.setTimeout("_queueManager_execute("+f+")",b);this.queue[f]=[b,c,d,e];return f};_queueManager.prototype.dequeue=function(b){this.queue[b]!=null&&(window.clearTimeout(this.queue[b][0]),this.queue[b]=null)};
function _queueManager_execute(b){if(goQueueManager.queue[b]!=null){var c=goQueueManager.queue[b][1],d=goQueueManager.queue[b][2];goQueueManager.queue[b][3]!=null?d.apply(c,goQueueManager.queue[b][3]):d.apply(c);goQueueManager.queue[b]=null}};var kaCurrentTool=null;function kaTool(b){this.kaMap=b;this.name="kaTool";this.bInfoTool=!1;this.wheelPlus=[b,b.zoomIn,null];this.wheelMinus=[b,b.zoomOut,null];this.kaMap.registerTool(this)}kaTool.prototype.isInfoTool=function(){return this.bInfoTool};kaTool.prototype.activate=function(){this.kaMap.activateTool(this);document.kaCurrentTool=this};kaTool.prototype.deactivate=function(){this.kaMap.deactivateTool(this);document.kaCurrentTool=null};kaTool.prototype.onmousemove=function(){return!1};
kaTool.prototype.onmousedown=function(){return!1};kaTool.prototype.onmouseup=function(){return!1};kaTool.prototype.ondblclick=function(){return!1};kaTool.prototype.setMouseWheel=function(b,c){this.wheelMinus=b;this.wheelPlus=c};kaTool.prototype.onmousewheel=function(b){var b=b?b:event?event:null,c=null;if(c=(b.wheelDelta?b.wheelDelta:b.detail*-1)>0?this.wheelPlus:this.wheelMinus)obj=c[0]?c[0]:null,func=c[1]?c[1]:null,args=c[2]?c[2]:null,func&&(args?func.apply(obj,args):func.apply(obj))};
kaTool.prototype.adjustPixPosition=function(b,c){for(var d=this.kaMap.domObj,e=0,f=0;d;)e+=parseInt(d.offsetLeft),f+=parseInt(d.offsetTop),d=d.offsetParent;d=parseInt(this.kaMap.theInsideLayer.style.left)+e-b;f=parseInt(this.kaMap.theInsideLayer.style.top)+f-c;return[d,f]};function kaTool_redirect_onkeypress(b){if(document.kaCurrentTool)document.kaCurrentTool.onkeypress(b)}
kaTool.prototype.onkeypress=function(b){if(b=b?b:event?event:null){var c=!0;switch(b.charCode?b.charCode:b.keyCode){case 38:this.kaMap.moveBy(0,16);this.kaMap.triggerEvent(KAMAP_EXTENTS_CHANGED,this.kaMap.getGeoExtents());break;case 40:this.kaMap.moveBy(0,-16);this.kaMap.triggerEvent(KAMAP_EXTENTS_CHANGED,this.kaMap.getGeoExtents());break;case 37:this.kaMap.moveBy(16,0);this.kaMap.triggerEvent(KAMAP_EXTENTS_CHANGED,this.kaMap.getGeoExtents());break;case 39:this.kaMap.moveBy(-16,0);this.kaMap.triggerEvent(KAMAP_EXTENTS_CHANGED,
this.kaMap.getGeoExtents());break;case 33:this.kaMap.slideBy(0,this.kaMap.viewportHeight/2);break;case 34:this.kaMap.slideBy(0,-this.kaMap.viewportHeight/2);break;case 36:this.kaMap.slideBy(this.kaMap.viewportWidth/2,0);break;case 35:this.kaMap.slideBy(-this.kaMap.viewportWidth/2,0);break;case 43:case 61:this.kaMap.zoomIn();break;case 45:this.kaMap.zoomOut();break;default:c=!1}return c?this.cancelEvent(b):!0}};kaTool.prototype.onmouseover=function(){return!1};
kaTool.prototype.onmouseout=function(){if(this.kaMap.isIE4)document.onkeydown=null;document.onkeypress=null;return!1};kaTool.prototype.cancelEvent=function(b){b=b?b:event?event:null;b.cancelBubble=!0;b.returnValue=!1;b.stopPropogation&&b.stopPropogation();b.preventDefault&&b.preventDefault();return!1};
function kaNavigator(b){kaTool.apply(this,[b]);this.name="kaNavigator";this.cursor=["url('KaMap/images/grab.cur'),move","-moz-grab","grab","move"];this.activeImage=this.kaMap.server+"images/button_pan_3.png";this.disabledImage=this.kaMap.server+"images/button_pan_2.png";for(var c in kaTool.prototype)kaNavigator.prototype[c]||(kaNavigator.prototype[c]=kaTool.prototype[c])}kaNavigator.prototype.onmouseout=null;kaNavigator.prototype.onmousemove=null;kaNavigator.prototype.onmousedown=null;
kaNavigator.prototype.onmouseup=null;kaNavigator.prototype.onclick=function(){return!0};var gDblClickTimer=kaNavigator.prototype.ondblclick=null;kaNavigator.prototype.dispatchMapClicked=function(b,c){var d=this.adjustPixPosition(b,c),d=this.kaMap.pixToGeo(d[0],d[1]);gDblClickTimer=null;this.kaMap.triggerEvent(KAMAP_MAP_CLICKED,d)};function bind(b,c){for(var d=arguments[0],e=arguments[1],f=[],g=2;g<arguments.length;g++)f.push(arguments[g]);return function(){return d.apply(e,f)}};var KAMAP_QUERY=gnLastEventId++,KAMAP_POINT_QUERY=0,KAMAP_RECT_QUERY=1;
function kaQuery(b,c){kaTool.apply(this,[b]);this.name="kaQuery";this.cursor="help";this.domObj=document.createElement("div");this.domObj.style.position="absolute";this.domObj.style.top="0px";this.domObj.style.left="0px";this.domObj.style.width="1px";this.domObj.style.height="1px";this.domObj.style.zIndex=100;this.domObj.style.visibility="hidden";this.domObj.style.border="1px solid red";this.domObj.style.backgroundColor="white";this.domObj.style.opacity=0.5;this.domObj.style.mozOpacity=0.5;this.domObj.style.filter=
"Alpha(opacity=50)";this.kaMap.theInsideLayer.appendChild(this.domObj);this.starty=this.startx=null;this.type=c;for(var d in kaTool.prototype)kaQuery.prototype[d]||(kaQuery.prototype[d]=kaTool.prototype[d])}
kaQuery.prototype.onclick=function(b){var b=b?b:event?event:null,c=KAMAP_POINT_QUERY,b=this.adjustPixPosition(b.pageX||b.clientX+(document.documentElement.scrollLeft||document.body.scrollLeft),b.pageY||b.clientY+(document.documentElement.scrollTop||document.body.scrollTop));this.startx=-b[0];this.starty=-b[1];b=this.kaMap.pixToGeo(this.startx,this.starty);this.kaMap.triggerEvent(KAMAP_QUERY,c,b);return!1};var KAMAP_MOUSE_TRACKER=gnLastEventId++,mousetrack_suspend=!1;function kaMouseTracker(b){kaTool.apply(this,[b]);this.name="kaMouseTracker";this.bInfoTool=!0;for(var c in kaTool.prototype)kaMouseTracker.prototype[c]||(kaMouseTracker.prototype[c]=kaTool.prototype[c])}
kaMouseTracker.prototype.onmousemove=function(b){b=b?b:event?event:null;if(mousetrack_suspend)return!1;b=this.kaMap.pixToGeo(b.pageX||b.clientX+(document.documentElement.scrollLeft||document.body.scrollLeft),b.pageY||b.clientY+(document.documentElement.scrollTop||document.body.scrollTop));this.kaMap.triggerEvent(KAMAP_MOUSE_TRACKER,{x:b[0],y:b[1]});return!1};function ScaleBar(b){this.scaleDenominator=b==null?1:b;this.displaySystem="metric";this.minWidth=100;this.maxWidth=200;this.subdivisions=this.divisions=2;this.singleLine=this.abbreviateLabel=this.showMinorMeasures=!1;this.resolution=72;this.align="center";this.container=document.createElement("div");this.container.className="sbWrapper";this.labelContainer=document.createElement("div");this.labelContainer.className="sbUnitsContainer";this.labelContainer.style.position="absolute";this.graphicsContainer=
document.createElement("div");this.graphicsContainer.style.position="absolute";this.graphicsContainer.className="sbGraphicsContainer";this.numbersContainer=document.createElement("div");this.numbersContainer.style.position="absolute";this.numbersContainer.className="sbNumbersContainer";b=document.createElement("div");b.className="sbMarkerMajor";this.graphicsContainer.appendChild(b);b=document.createElement("div");b.className="sbMarkerMinor";this.graphicsContainer.appendChild(b);b=document.createElement("div");
b.className="sbBar";this.graphicsContainer.appendChild(b);b=document.createElement("div");b.className="sbBarAlt";this.graphicsContainer.appendChild(b)}
ScaleBar.prototype.update=function(b){function c(b,c,d){for(var d=d==null?10:d,e=Number.POSITIVE_INFINITY,f=Number.POSITIVE_INFINITY,g=b,h=3,j=0;j<3;++j)for(var k=Math.pow(2,-1*j),l=Math.floor(Math.log(c/k)/Math.LN10),m=l;m>l-d+1;--m){var o=Math.max(j-m,0),n=k*Math.pow(10,m);if(n*Math.floor(c/n)>=b){var q=b%n==0?b/n:Math.floor(b/n)+1,p=q+2*j,r=m<0?Math.abs(m)+1:m;if(p<e||p==e&&r<f)e=p,f=r,g=(n*q).toFixed(o),h=o}}this.value=g;this.score=e;this.tieBreaker=f;this.numDec=h}function d(b,c){var d=0;if(document.styleSheets)for(var e=
document.styleSheets.length-1;e>=0;--e){var f=document.styleSheets[e];if(!f.disabled){if(typeof f.cssrules=="undefined")if(typeof f.rules=="undefined")return 0;else f=f.rules;else f=f.cssRules;for(var g=0;g<f.length;++g){var h=f[g];h.selectorText&&h.selectorText.toLowerCase()==b.toLowerCase()&&h.style[c]!=""&&(d=parseInt(h.style[c]))}}}return d?d:0}if(b!=null)this.scaleDenominator=b;c.prototype.toString=function(){return this.value.toString()};c.prototype.valueOf=function(){return this.value};this.container.title=
"scale 1:"+function(b,c){for(var c=c?c:0,d=""+Math.round(b),e=/(-?[0-9]+)([0-9]{3})/;e.test(d);)d=d.replace(e,"$1,$2");return c>0?(e=Math.floor(Math.pow(10,c)*(b-Math.round(b))),e==0?d:d+"."+e):d}(this.scaleDenominator);for(var e={english:{units:["miles","feet","inches"],abbr:["mi","ft","in"],inches:[63360,12,1]},metric:{units:["kilometers","meters","centimeters"],abbr:["km","m","cm"],inches:[39370.07874,39.370079,0.393701]}},f=[],g=0;g<e[this.displaySystem].units.length;++g){f[g]={};for(var k=this.resolution*
e[this.displaySystem].inches[g]/this.scaleDenominator,b=this.minWidth/k/(this.divisions*this.subdivisions),o=this.maxWidth/k/(this.divisions*this.subdivisions),j=0;j<this.divisions*this.subdivisions;++j){k=new c(b*(j+1),o*(j+1));f[g][j]={value:k.value/(j+1),score:0,tieBreaker:0,numDec:0,displayed:0};for(var l=0;l<this.divisions*this.subdivisions;++l){displayedValuePosition=k.value*(l+1)/(j+1);niceNumber2=new c(displayedValuePosition,displayedValuePosition);var n=(l+1)%this.subdivisions==0,q=l+1==
this.divisions*this.subdivisions;this.singleLine&&q||!this.singleLine&&(n||this.showMinorMeasures)?(f[g][j].score+=niceNumber2.score,f[g][j].tieBreaker+=niceNumber2.tieBreaker,f[g][j].numDec=Math.max(f[g][j].numDec,niceNumber2.numDec),f[g][j].displayed+=1):(f[g][j].score+=niceNumber2.score/this.subdivisions,f[g][j].tieBreaker+=niceNumber2.tieBreaker/this.subdivisions)}f[g][j].score*=(g+1)*f[g][j].tieBreaker/f[g][j].displayed}}for(var k=o=b=l=null,s=q=Number.POSITIVE_INFINITY,g=n=0;g<f.length;++g)for(j in f[g])if(f[g][j].score<
q||f[g][j].score==q&&f[g][j].tieBreaker<s)q=f[g][j].score,s=f[g][j].tieBreaker,l=f[g][j].value,n=f[g][j].numDec,b=e[this.displaySystem].units[g],o=e[this.displaySystem].abbr[g],k=this.resolution*e[this.displaySystem].inches[g]/this.scaleDenominator,k*=l;f=(d(".sbMarkerMajor","borderLeftWidth")+d(".sbMarkerMajor","width")+d(".sbMarkerMajor","borderRightWidth"))/2;g=(d(".sbMarkerMinor","borderLeftWidth")+d(".sbMarkerMinor","width")+d(".sbMarkerMinor","borderRightWidth"))/2;q=(d(".sbBar","borderLeftWidth")+
d(".sbBar","borderRightWidth"))/2;s=(d(".sbBarAlt","borderLeftWidth")+d(".sbBarAlt","borderRightWidth"))/2;document.styleSheets||(g=f=0.5);for(;this.labelContainer.hasChildNodes();)this.labelContainer.removeChild(this.labelContainer.firstChild);for(;this.graphicsContainer.hasChildNodes();)this.graphicsContainer.removeChild(this.graphicsContainer.firstChild);for(;this.numbersContainer.hasChildNodes();)this.numbersContainer.removeChild(this.numbersContainer.firstChild);for(var h,m,j={left:0,center:-1*
this.divisions*this.subdivisions*k/2,right:-1*this.divisions*this.subdivisions*k},e=0+j[this.align],p=m=0;p<this.divisions;++p){e=p*this.subdivisions*k;e+=j[this.align];m=p==0?0:(p*this.subdivisions*l).toFixed(n);h=document.createElement("div");h.className="sbMarkerMajor";h.style.position="absolute";h.style.overflow="hidden";h.style.left=Math.round(e-f)+"px";h.appendChild(document.createTextNode(" "));this.graphicsContainer.appendChild(h);if(!this.singleLine)h=document.createElement("div"),h.className=
"sbNumbersBox",h.style.position="absolute",h.style.overflow="hidden",h.style.textAlign="center",this.showMinorMeasures?(h.style.width=Math.round(k*2)+"px",h.style.left=Math.round(e-k)+"px"):(h.style.width=Math.round(this.subdivisions*k*2)+"px",h.style.left=Math.round(e-this.subdivisions*k)+"px"),h.appendChild(document.createTextNode(m)),this.numbersContainer.appendChild(h);for(var r=0;r<this.subdivisions;++r)if(m=document.createElement("div"),m.style.position="absolute",m.style.overflow="hidden",
m.style.width=Math.round(k)+"px",r%2==0?(m.className="sbBar",m.style.left=Math.round(e-q)+"px"):(m.className="sbBarAlt",m.style.left=Math.round(e-s)+"px"),m.appendChild(document.createTextNode(" ")),this.graphicsContainer.appendChild(m),r<this.subdivisions-1&&(e=(p*this.subdivisions+(r+1))*k,e+=j[this.align],m=(p*this.subdivisions+r+1)*l,h=document.createElement("div"),h.className="sbMarkerMinor",h.style.position="absolute",h.style.overflow="hidden",h.style.left=Math.round(e-g)+"px",h.appendChild(document.createTextNode(" ")),
this.graphicsContainer.appendChild(h),this.showMinorMeasures&&!this.singleLine))h=document.createElement("div"),h.className="sbNumbersBox",h.style.position="absolute",h.style.overflow="hidden",h.style.textAlign="center",h.style.width=Math.round(k*2)+"px",h.style.left=Math.round(e-k)+"px",h.appendChild(document.createTextNode(m)),this.numbersContainer.appendChild(h)}e=this.divisions*this.subdivisions*k;e+=j[this.align];m=(this.divisions*this.subdivisions*l).toFixed(n);h=document.createElement("div");
h.className="sbMarkerMajor";h.style.position="absolute";h.style.overflow="hidden";h.style.left=Math.round(e-f)+"px";h.appendChild(document.createTextNode(" "));this.graphicsContainer.appendChild(h);if(!this.singleLine)h=document.createElement("div"),h.className="sbNumbersBox",h.style.position="absolute",h.style.overflow="hidden",h.style.textAlign="center",this.showMinorMeasures?(h.style.width=Math.round(k*2)+"px",h.style.left=Math.round(e-k)+"px"):(h.style.width=Math.round(this.subdivisions*k*2)+
"px",h.style.left=Math.round(e-this.subdivisions*k)+"px"),h.appendChild(document.createTextNode(m)),this.numbersContainer.appendChild(h);l=document.createElement("div");l.style.position="absolute";this.singleLine?(n=m,l.className="sbLabelBoxSingleLine",l.style.top="-0.6em",l.style.left=e+10+"px"):(n="",l.className="sbLabelBox",l.style.textAlign="center",l.style.width=Math.round(this.divisions*this.subdivisions*k)+"px",l.style.left=Math.round(j[this.align])+"px",l.style.overflow="hidden");n+=this.abbreviateLabel?
" "+o:" "+b;l.appendChild(document.createTextNode(n));this.labelContainer.appendChild(l);if(!document.styleSheets)b=document.createElement("style"),b.type="text/css",o=".sbBar {top: 0px; background: #666666; height: 1px; border: 0;}",o+=".sbBarAlt {top: 0px; background: #666666; height: 1px; border: 0;}",o+=".sbMarkerMajor {height: 7px; width: 1px; background: #666666; border: 0;}",o+=".sbMarkerMinor {height: 5px; width: 1px; background: #666666; border: 0;}",o+=".sbLabelBox {top: -16px;}",o+=".sbNumbersBox {top: 7px;}",
b.appendChild(document.createTextNode(o)),document.getElementsByTagName("head").item(0).appendChild(b);this.container.appendChild(this.graphicsContainer);this.container.appendChild(this.labelContainer);this.container.appendChild(this.numbersContainer)};ScaleBar.prototype.place=function(b){b==null?document.body.appendChild(this.container):(b=document.getElementById(b),b!=null&&b.appendChild(this.container));this.update()};
